import React, { useState } from 'react';
import { X, Printer, Send, CheckCircle2 } from 'lucide-react';

export default function DispatchModal({ evacuationPlan, onClose }) {
  const [smsSent, setSmsSent] = useState(false);

  const totalCitizens = evacuationPlan.reduce((sum, item) => sum + item.evacuee_count, 0);

  const handlePrint = () => {
    window.print();
  };

  const handleSendSMS = () => {
    setSmsSent(true);
    setTimeout(() => setSmsSent(false), 4000);
  };

  return (
    <div style={{
      position: 'fixed',
      inset: 0,
      background: 'rgba(5, 10, 24, 0.85)',
      backdropFilter: 'blur(8px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 2000,
      padding: '16px'
    }}>
      <div className="glass-card" style={{ maxWidth: '820px', width: '100%', maxHeight: '90vh', overflowY: 'auto', padding: '28px', position: 'relative', border: '1px solid rgba(59, 130, 246, 0.4)' }}>
        {/* Close */}
        <button
          onClick={onClose}
          style={{ position: 'absolute', top: '20px', right: '20px', background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer' }}
        >
          <X size={22} />
        </button>

        {/* Government Header */}
        <div style={{ textAlign: 'center', borderBottom: '2px solid rgba(59,130,246,0.3)', paddingBottom: '16px', marginBottom: '20px' }}>
          <div style={{ fontSize: '11px', letterSpacing: '1px', fontWeight: 'bold', color: '#94a3b8', textTransform: 'uppercase' }}>
            Government of India &bull; Ministry of Home Affairs
          </div>
          <h1 style={{ fontSize: '17px', fontWeight: '800', color: '#f8fafc', marginTop: '4px' }}>
            NATIONAL DISASTER RESPONSE FORCE &bull; DISASTER MANAGEMENT DIVISION
          </h1>
          <div style={{ fontSize: '13px', color: '#38bdf8', fontWeight: 'bold', marginTop: '2px' }}>
            OFFICIAL PREEMPTIVE CONVOY RELOCATION &amp; RECEIVING MANIFEST
          </div>
          <div style={{ fontSize: '11px', color: '#64748b', marginTop: '4px' }}>
            Generated by ResQGrid AI Platform &bull; Authorized under Section 34, DM Act 2005
          </div>
        </div>

        {/* Summary Chips */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '12px', marginBottom: '20px' }}>
          <div style={{ background: 'rgba(11, 19, 41, 0.7)', padding: '10px 14px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.08)' }}>
            <div style={{ fontSize: '10.5px', color: '#94a3b8' }}>TOTAL MOBILIZED CITIZENS</div>
            <div style={{ fontSize: '20px', fontWeight: 'bold', color: '#f8fafc', marginTop: '2px' }}>
              {totalCitizens.toLocaleString()}
            </div>
          </div>

          <div style={{ background: 'rgba(11, 19, 41, 0.7)', padding: '10px 14px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.08)' }}>
            <div style={{ fontSize: '10.5px', color: '#94a3b8' }}>ACTIVE CONVOY CORRIDORS</div>
            <div style={{ fontSize: '20px', fontWeight: 'bold', color: '#38bdf8', marginTop: '2px' }}>
              {evacuationPlan.length} Convoys
            </div>
          </div>

          <div style={{ background: 'rgba(11, 19, 41, 0.7)', padding: '10px 14px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.08)' }}>
            <div style={{ fontSize: '10.5px', color: '#94a3b8' }}>SHELTER OVERFLOW</div>
            <div style={{ fontSize: '20px', fontWeight: 'bold', color: '#10b981', marginTop: '2px' }}>
              0% (Zero Overflow)
            </div>
          </div>
        </div>

        {/* Manifest Table */}
        <div style={{ overflowX: 'auto', marginBottom: '20px' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11.5px', color: '#cbd5e1' }}>
            <thead>
              <tr style={{ background: 'rgba(30, 58, 138, 0.4)', borderBottom: '1px solid rgba(59,130,246,0.3)', textAlign: 'left' }}>
                <th style={{ padding: '10px 8px' }}>Convoy ID</th>
                <th style={{ padding: '10px 8px' }}>Origin (Red Zone)</th>
                <th style={{ padding: '10px 8px' }}>Destination Shelter</th>
                <th style={{ padding: '10px 8px' }}>Headcount</th>
                <th style={{ padding: '10px 8px' }}>Distance / ETA</th>
                <th style={{ padding: '10px 8px' }}>Fleet Vehicles</th>
                <th style={{ padding: '10px 8px' }}>Status</th>
              </tr>
            </thead>
            <tbody>
              {evacuationPlan.map((item, idx) => (
                <tr key={idx} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)', background: idx % 2 === 0 ? 'rgba(11,19,41,0.3)' : 'transparent' }}>
                  <td style={{ padding: '9px 8px', fontWeight: 'bold', color: '#60a5fa' }}>NDRF-{101 + idx}</td>
                  <td style={{ padding: '9px 8px', fontWeight: '600', color: '#f8fafc' }}>{item.from_name}</td>
                  <td style={{ padding: '9px 8px', color: '#38bdf8' }}>{item.to_name}</td>
                  <td style={{ padding: '9px 8px', fontWeight: 'bold', color: '#f8fafc' }}>{item.evacuee_count}</td>
                  <td style={{ padding: '9px 8px' }}>{item.distance_km} km ({item.estimated_transit_mins}m)</td>
                  <td style={{ padding: '9px 8px', fontSize: '10.5px' }}>{item.recommended_convoy_type}</td>
                  <td style={{ padding: '9px 8px', color: '#34d399', fontWeight: 'bold' }}>APPROVED</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* SMS Broadcast Notification */}
        {smsSent && (
          <div style={{ background: 'rgba(16, 185, 129, 0.2)', border: '1px solid #10b981', color: '#a7f3d0', padding: '10px 14px', borderRadius: '6px', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
            <CheckCircle2 size={16} />
            <span>Compressed 160-char SMS Dispatch broadcasted successfully to 142 Aapda Mitra Volunteers & NDRF Unit Commanders over 2G/EDGE mesh.</span>
          </div>
        )}

        {/* Action Buttons */}
        <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '10px', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '16px' }}>
          <div style={{ fontSize: '11px', color: '#94a3b8' }}>
            District Emergency Operation Center &bull; Verified Digital Seal
          </div>

          <div style={{ display: 'flex', gap: '10px' }}>
            <button
              onClick={handleSendSMS}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                background: 'rgba(245, 158, 11, 0.2)',
                color: '#f59e0b',
                border: '1px solid rgba(245, 158, 11, 0.4)',
                padding: '8px 16px',
                borderRadius: '6px',
                fontSize: '12px',
                fontWeight: 'bold',
                cursor: 'pointer'
              }}
            >
              <Send size={15} />
              <span>Broadcast Field SMS</span>
            </button>

            <button
              onClick={handlePrint}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                background: '#2563eb',
                color: 'white',
                border: 'none',
                padding: '8px 18px',
                borderRadius: '6px',
                fontSize: '12px',
                fontWeight: 'bold',
                cursor: 'pointer'
              }}
            >
              <Printer size={15} />
              <span>Print Official PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
